@host = http://localhost:5238

POST {{host}}/api/auth/login
Content-Type: application/json
{
  "firstName": "Johntestsss",
  "lastName": "Doe",
  "email": "johndoe@esmail123.com",
  "password": "password123"
}

###
